name: Playwright Java Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install Java 22 (Temurin)
      - name: Set up Java 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
      - run: java -version   # verify Java 22 is active
      - run: mvn -version    # verify Maven is using Java 22

      # Step 3: Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Install dependencies
      - name: Build project
        run: mvn install -DskipTests

      # Step 5: Install Playwright browsers
      - name: Install Playwright Browsers
        run: mvn exec:java -e -Dexec.mainClass="com.microsoft.playwright.CLI" -Dexec.args="install"

      # Step 6: Run Playwright tests
      - name: Run Playwright tests
        run: mvn test
